# Generated by Django 4.2.7 on 2023-12-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoritablosu',
            fields=[
                ('checkbox_id', models.AutoField(db_column='checkbox_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('is_checked', models.IntegerField(blank=True, null=True)),
                ('pazaryeri', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'kategoritablosu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productjson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_context', models.CharField(blank=True, db_column='@context', max_length=400, null=True)),
                ('field_type', models.CharField(blank=True, db_column='@type', max_length=400, null=True)),
                ('field_id', models.CharField(blank=True, db_column='@id', max_length=400, null=True)),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('image', models.CharField(blank=True, max_length=400, null=True)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('sku', models.CharField(blank=True, max_length=400, null=True)),
                ('gtin13', models.CharField(blank=True, max_length=400, null=True)),
                ('brand_type', models.CharField(blank=True, db_column='brand.@type', max_length=400, null=True)),
                ('brandname', models.CharField(blank=True, max_length=400, null=True)),
                ('url', models.CharField(blank=True, max_length=400, null=True)),
                ('offers_type', models.CharField(blank=True, db_column='offers.@type', max_length=400, null=True)),
                ('offers_url', models.CharField(blank=True, db_column='offers.url', max_length=400, null=True)),
                ('offers_pricecurrency', models.CharField(blank=True, db_column='offers.priceCurrency', max_length=400, null=True)),
                ('offers_price', models.CharField(blank=True, db_column='offers.price', max_length=400, null=True)),
                ('offers_itemcondition', models.CharField(blank=True, db_column='offers.itemCondition', max_length=400, null=True)),
                ('offers_availability', models.CharField(blank=True, db_column='offers.availability', max_length=400, null=True)),
                ('aggregaterating_type', models.CharField(blank=True, db_column='aggregateRating.@type', max_length=400, null=True)),
                ('aggregaterating_ratingvalue', models.CharField(blank=True, db_column='aggregateRating.ratingValue', max_length=20, null=True)),
                ('aggregaterating_ratingcount', models.CharField(blank=True, db_column='aggregateRating.ratingCount', max_length=20, null=True)),
                ('aggregaterating_reviewcount', models.CharField(blank=True, db_column='aggregateRating.reviewCount', max_length=20, null=True)),
            ],
            options={
                'db_table': 'productjson',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('idusers', models.AutoField(db_column='idUsers', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='Username', max_length=45, null=True, unique=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=45, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
